#line 1 "eiffel.flex.c"

#line 3 "eiffel.flex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[367] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       64,   62,   61,   61,   48,    4,   49,    1,   38,   39,
       34,   32,   46,   33,   45,   35,   56,   56,   44,   37,
       19,   13,   21,   47,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   42,   31,   43,   36,   40,   62,   41,   15,
       63,    2,    2,    2,    3,    5,    5,    6,   62,   10,
       11,   61,    9,   18,    0,   30,   14,   16,    0,   56,
        0,    0,    0,    0,    0,   12,   20,   22,   54,   54,
       54,   54,   50,   54,   54,   54,   54,   54,   54,   54,

       50,   54,   54,   54,   54,   54,   54,   50,   54,   54,
       50,   54,   54,   54,   54,   54,   54,   25,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,    0,
        8,    8,   60,   60,   60,   60,   60,   59,   58,    0,
       55,   57,   54,   54,   50,   23,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   50,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       26,   54,   50,   54,   54,    0,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   24,    0,    0,    0,    0,   60,   60,   59,

        0,   58,    0,   57,    0,   54,   54,    0,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   50,   54,   54,
       54,   54,   54,   54,   50,   54,   54,   54,   54,   54,
       50,   54,   50,   50,   54,   50,   50,    0,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   50,   51,   54,
       54,   54,   54,   53,   50,   17,    7,    0,    0,    0,
       50,   50,    0,   54,   54,   50,   50,   54,   54,   54,
       50,   54,   54,   54,   54,   54,   54,   52,   54,   54,
       54,   54,   54,   54,   50,   54,    0,   54,   54,   54,
       54,   54,   54,   50,   54,   54,   50,   54,   50,   54,

        0,    0,   50,   54,   54,   50,   54,   54,   50,   50,
       54,   50,   54,   54,   50,   54,   54,   54,   54,   54,
        0,   54,   54,   50,   54,   50,   50,   50,   54,   54,
       54,    0,   54,   50,   50,   54,   54,   54,   50,   29,
       50,   50,   54,   54,   28,   54,   54,   50,   54,   54,
       50,   27,   54,   50,   50,   50,   54,   50,   54,   50,
       50,   50,   50,   50,   50,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,    1,   58,   59,   60,   61,

       62,   63,   64,   65,   66,   36,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
       81,   82,   83,   84,   85,   86,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[87] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    1,    4,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1,    6,    4,    4,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[376] =
    {   0,
        0,    0,  339,  321,   84,   86,   92,   93,  287,  278,
      264,  889,   99,  101,  889,  889,  889,  889,  889,  889,
      889,  889,  889,  221,   90,   90,  162,   98,  205,  889,
      182,  889,  177,  889,   86,    0,  101,   81,   83,  140,
      125,  133,   49,  169,   67,   96,   97,  171,  133,  169,
      151,  146,  889,  889,  889,  889,  889,  171,  889,  889,
      889,  889,  889,  167,  889,  889,  889,  889,  133,  889,
      889,  134,  889,  889,  213,  889,  889,  889,  232,  238,
      129,  242,  254,    0,  259,  889,  889,  889,    0,  158,
      245,  162,  163,  165,  203,  227,  222,  236,  238,  256,

        0,  242,  259,  251,  253,  272,  255,    0,  259,  280,
        0,  265,  277,  257,  260,  277,  311,  223,  277,  311,
      305,  291,  282,  294,  314,  302,  317,  330,  306,  129,
      889,  345,  889,  376,  385,  391,  395,  229,  399,  350,
      402,   83,  358,  373,    0,  307,  366,  362,  394,  380,
      381,  400,  386,  387,  404,  406,    0,  392,  420,  409,
      397,  397,  410,  406,  414,  408,  419,  420,  426,  421,
      434,  426,    0,  439,  424,  483,  452,  456,  461,  436,
      460,  450,  459,  468,  458,  468,  464,  469,  468,  469,
      478,  466,    0,   54,  524,  529,  533,  537,  544,  541,

      548,  552,  555,   77,   73,  521,  531,  575,  546,  545,
      546,  539,  554,  541,  557,  556,  548,  558,  551,  556,
      556,  558,  572,  560,    0,  573,  573,  571,  587,  579,
        0,  589,    0,    0,  590,    0,    0,  591,  584,  601,
      597,  603,  593,  603,  591,  614,  602,    0,    0,  613,
      615,  612,  621,    0,    0,  889,  889,  665,  669,  673,
        0,    0,  629,  625,  639,    0,    0,  629,  637,  637,
        0,  653,  669,  671,  674,  660,  668,    0,  665,  670,
      680,  677,  684,  679,    0,  684,  672,  674,  684,  689,
      678,  692,  679,    0,  682,  702,    0,  699,    0,  697,

      109,  710,    0,  702,  707,    0,  710,  726,    0,    0,
      728,    0,  734,  731,    0,  719,  720,  722,  742,  725,
      742,  730,  736,    0,  746,    0,    0,    0,  734,  741,
      736,  744,  739,    0,    0,  748,  757,  751,    0,    0,
        0,    0,  751,  764,  889,  756,  768,    0,  771,  772,
        0,  889,  776,    0,    0,    0,  767,    0,  772,    0,
        0,    0,    0,    0,    0,  889,  846,  852,  858,  864,
      867,  873,  879,   84,  882
    } ;

static const flex_int16_t yy_def[376] =
    {   0,
      366,    1,  367,  367,  368,  368,  369,  369,  370,  370,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  372,  366,  366,  366,  366,  372,  366,
      366,  366,  366,  366,  373,  366,  366,  366,  373,  366,
      366,  366,  366,  374,  366,  366,  366,  366,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  366,
      366,  366,  366,  373,  366,  366,  373,  366,  366,  366,
      366,  375,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  366,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  366,  366,  373,  366,  373,  366,  366,

      366,  366,  366,  375,  375,  371,  371,  366,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  366,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  366,  366,  366,  373,  366,
      371,  371,  366,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  366,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      366,  366,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      366,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  366,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  366,  371,  371,  371,  371,  371,
      371,  366,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,    0,  366,  366,  366,  366,
      366,  366,  366,  366,  366
    } ;

static const flex_int16_t yy_nxt[976] =
    {   0,
       12,   13,   14,   15,   16,   17,   12,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   28,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   36,   36,   41,   36,   36,   42,   36,   43,
       44,   45,   36,   46,   47,   48,   49,   50,   51,   52,
       36,   36,   53,   54,   55,   56,   12,   35,   36,   37,
       38,   39,   40,   36,   36,   41,   36,   42,   36,   43,
       44,   45,   36,   46,   47,   48,   49,   50,   51,   52,
       36,   36,   57,   58,   59,   60,   63,  142,   63,  114,
       64,   65,   64,   65,   67,   67,   68,   68,   69,   69,

       72,   72,   72,   72,   74,   76,   75,   75,   75,   75,
      119,  100,   79,   77,   80,   80,   80,   80,   90,  114,
      102,  101,  103,   91,  257,   92,  120,  121,   83,  205,
       93,   94,  104,  205,   95,   72,   72,  256,   96,  205,
      119,   97,  100,  194,   98,  138,  138,   99,  132,   90,
      102,  101,  103,   91,   85,   92,  108,  120,  121,   83,
       93,   94,  104,  109,  110,   95,  105,  112,   96,  111,
      106,   97,  125,  113,   98,   78,   79,   99,   80,   80,
       80,   80,  132,  107,  128,  130,  129,  108,  143,   81,
       82,  146,   83,  109,  110,  126,  115,  105,  112,  111,

       88,  106,  125,  113,  122,   87,  116,  147,  117,  127,
      148,   84,  118,  107,  123,  128,  129,  124,   85,  143,
       81,   82,  146,   83,  176,  176,  126,  115,   86,  134,
      134,  134,  134,  149,   73,  122,  116,  147,  117,  127,
      148,   84,  118,  135,  123,  200,  200,  124,  137,  137,
      137,  137,   79,  150,   80,   80,   80,   80,  139,  139,
      139,  151,  135,  366,  149,  140,  152,  140,   83,  136,
      141,  141,  141,  141,  135,   80,   80,   80,   80,  144,
       71,  153,  145,  154,  150,  201,  156,  155,  157,   71,
      161,  151,  159,  135,   85,  163,  160,  152,  162,   83,

      164,  168,  171,  158,  172,  169,  173,  177,  208,  208,
      144,  153,  145,  165,  154,   85,  156,  170,  155,  157,
      161,  185,  159,   61,  166,  163,  160,  167,  186,  162,
      164,  168,  171,  158,  172,  187,  169,  173,  177,  174,
      178,   61,  183,  188,  165,  190,  184,  170,  175,  193,
      179,  191,  185,  180,  166,  181,  182,  167,  186,  189,
      192,  195,  195,  195,  195,  187,  141,  141,  141,  141,
      174,  178,  183,  366,  188,  190,  184,  366,  175,  193,
      179,  366,  191,  180,  366,  181,  182,  366,  366,  189,
      366,  192,  134,  134,  134,  134,  140,  206,  140,  207,

      209,  141,  141,  141,  141,  210,  135,  196,  196,  196,
      196,  198,  198,  198,  198,  202,  202,  202,  141,  141,
      141,  141,  211,  366,  212,  135,  214,  206,  213,  215,
      207,  209,  136,  216,  217,  210,  218,  135,  219,  222,
      366,  223,  224,  227,  228,  230,  220,  197,  225,  229,
      231,  199,  232,  211,  212,  203,  135,  214,  213,  215,
      221,  226,  233,  216,  234,  217,  235,  218,  219,  236,
      222,  223,  224,  227,  237,  228,  230,  220,  225,  229,
      239,  231,  242,  232,  176,  176,  240,  241,  243,  246,
      221,  226,  233,  245,  247,  234,  235,  248,  249,  251,

      236,  250,  252,  253,  237,  255,  244,  254,  366,  366,
      366,  239,  242,  238,  366,  366,  366,  240,  241,  243,
      246,  366,  366,  245,  366,  247,  366,  248,  366,  249,
      251,  250,  366,  252,  253,  255,  244,  366,  254,  257,
      258,  258,  258,  258,  238,  134,  134,  134,  134,  196,
      196,  196,  196,  198,  198,  198,  198,  200,  200,  135,
      259,  259,  259,  259,  200,  200,  261,  135,  202,  202,
      202,  202,  202,  202,  366,  262,  208,  208,  264,  265,
      366,  366,  266,  267,  268,  136,  269,  270,  271,  197,
      135,  272,  273,  199,  274,  275,  261,  201,  135,  276,

      260,  277,  278,  280,  201,  262,  279,  281,  203,  264,
      265,  203,  266,  267,  282,  268,  269,  283,  270,  271,
      263,  272,  284,  273,  274,  275,  285,  286,  287,  276,
      288,  277,  289,  278,  280,  290,  279,  291,  281,  292,
      293,  294,  295,  297,  282,  296,  298,  300,  283,  299,
      263,  366,  284,  366,  366,  366,  285,  286,  287,  366,
      288,  366,  302,  289,  303,  290,  304,  306,  291,  292,
      293,  294,  305,  295,  297,  296,  307,  298,  300,  299,
      257,  301,  301,  301,  301,  198,  198,  198,  198,  259,
      259,  259,  259,  302,  303,  366,  308,  304,  306,  135,

      309,  310,  305,  311,  366,  312,  307,  313,  314,  315,
      316,  317,  318,  319,  320,  366,  321,  322,  323,  324,
      366,  325,  326,  366,  327,  199,  308,  328,  329,  260,
      135,  309,  310,  330,  311,  312,  331,  313,  314,  315,
      332,  316,  317,  318,  319,  320,  321,  322,  333,  323,
      324,  325,  334,  326,  327,  335,  336,  328,  337,  329,
      338,  339,  366,  340,  330,  341,  331,  342,  343,  366,
      344,  332,  345,  366,  346,  347,  348,  354,  333,  349,
      350,  351,  334,  352,  353,  335,  355,  336,  356,  337,
      357,  338,  339,  340,  358,  341,  359,  342,  360,  343,

      344,  361,  362,  345,  346,  347,  363,  348,  354,  349,
      350,  351,  364,  352,  353,  365,  366,  355,  356,  366,
      357,  366,  366,  366,  366,  358,  359,  366,  366,  360,
      366,  366,  361,  362,  366,  366,  366,  363,  366,  366,
      366,  366,  364,  366,  366,  365,   12,   12,   12,   12,
       12,   12,   62,   62,   62,   62,   62,   62,   66,   66,
       66,   66,   66,   66,   70,   70,   70,   70,   70,   70,
       89,   89,   89,  131,  366,  131,  131,  131,  131,  133,
      133,  366,  133,  133,  133,  204,  366,  204,   11,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366
    } ;

static const flex_int16_t yy_chk[976] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,  374,    6,   43,
        5,    5,    6,    6,    7,    8,    7,    8,    7,    8,

       13,   13,   14,   14,   25,   26,   25,   25,   25,   25,
       45,   38,   28,   26,   28,   28,   28,   28,   35,   43,
       39,   38,   39,   35,  301,   35,   46,   47,   28,  205,
       35,   35,   39,  204,   37,   72,   72,  194,   37,  142,
       45,   37,   38,  130,   37,   81,   81,   37,   69,   35,
       39,   38,   39,   35,   28,   35,   41,   46,   47,   28,
       35,   35,   39,   41,   41,   37,   40,   42,   37,   41,
       40,   37,   49,   42,   37,   26,   27,   37,   27,   27,
       27,   27,   64,   40,   51,   58,   52,   41,   90,   27,
       27,   92,   27,   41,   41,   50,   44,   40,   42,   41,

       33,   40,   49,   42,   48,   31,   44,   93,   44,   50,
       94,   27,   44,   40,   48,   51,   52,   48,   27,   90,
       27,   27,   92,   27,  118,  118,   50,   44,   29,   75,
       75,   75,   75,   95,   24,   48,   44,   93,   44,   50,
       94,   27,   44,   75,   48,  138,  138,   48,   79,   79,
       79,   79,   80,   96,   80,   80,   80,   80,   82,   82,
       82,   97,   79,   11,   95,   83,   98,   83,   80,   75,
       83,   83,   83,   83,   75,   85,   85,   85,   85,   91,
       10,   99,   91,  100,   96,  138,  102,  100,  103,    9,
      105,   97,  104,   79,   80,  107,  104,   98,  106,   80,

      109,  112,  114,  103,  115,  113,  116,  119,  146,  146,
       91,   99,   91,  110,  100,   85,  102,  113,  100,  103,
      105,  122,  104,    4,  110,  107,  104,  110,  123,  106,
      109,  112,  114,  103,  115,  124,  113,  116,  119,  117,
      120,    3,  121,  125,  110,  126,  121,  113,  117,  129,
      120,  127,  122,  120,  110,  120,  120,  110,  123,  125,
      128,  132,  132,  132,  132,  124,  140,  140,  140,  140,
      117,  120,  121,    0,  125,  126,  121,    0,  117,  129,
      120,    0,  127,  120,    0,  120,  120,    0,    0,  125,
        0,  128,  134,  134,  134,  134,  135,  143,  135,  144,

      147,  135,  135,  135,  135,  148,  134,  136,  136,  136,
      136,  137,  137,  137,  137,  139,  139,  139,  141,  141,
      141,  141,  149,    0,  150,  137,  152,  143,  151,  153,
      144,  147,  134,  154,  155,  148,  156,  134,  158,  160,
        0,  161,  162,  164,  165,  167,  159,  136,  163,  166,
      168,  137,  169,  149,  150,  139,  137,  152,  151,  153,
      159,  163,  170,  154,  171,  155,  172,  156,  158,  174,
      160,  161,  162,  164,  175,  165,  167,  159,  163,  166,
      177,  168,  180,  169,  176,  176,  178,  179,  181,  183,
      159,  163,  170,  182,  184,  171,  172,  185,  186,  188,

      174,  187,  189,  190,  175,  192,  181,  191,    0,    0,
        0,  177,  180,  176,    0,    0,    0,  178,  179,  181,
      183,    0,    0,  182,    0,  184,    0,  185,    0,  186,
      188,  187,    0,  189,  190,  192,  181,    0,  191,  195,
      195,  195,  195,  195,  176,  196,  196,  196,  196,  197,
      197,  197,  197,  198,  198,  198,  198,  200,  200,  196,
      199,  199,  199,  199,  201,  201,  206,  198,  202,  202,
      202,  203,  203,  203,    0,  207,  208,  208,  209,  210,
        0,    0,  211,  212,  213,  196,  214,  215,  216,  197,
      196,  217,  218,  198,  219,  220,  206,  200,  198,  221,

      199,  222,  223,  226,  201,  207,  224,  227,  202,  209,
      210,  203,  211,  212,  228,  213,  214,  229,  215,  216,
      208,  217,  230,  218,  219,  220,  232,  235,  238,  221,
      239,  222,  240,  223,  226,  241,  224,  242,  227,  243,
      244,  245,  246,  250,  228,  247,  251,  253,  229,  252,
      208,    0,  230,    0,    0,    0,  232,  235,  238,    0,
      239,    0,  263,  240,  264,  241,  265,  269,  242,  243,
      244,  245,  268,  246,  250,  247,  270,  251,  253,  252,
      258,  258,  258,  258,  258,  259,  259,  259,  259,  260,
      260,  260,  260,  263,  264,    0,  272,  265,  269,  259,

      273,  274,  268,  275,    0,  276,  270,  277,  279,  280,
      281,  282,  283,  284,  286,    0,  287,  288,  289,  290,
        0,  291,  292,    0,  293,  259,  272,  295,  296,  260,
      259,  273,  274,  298,  275,  276,  300,  277,  279,  280,
      302,  281,  282,  283,  284,  286,  287,  288,  304,  289,
      290,  291,  305,  292,  293,  307,  308,  295,  311,  296,
      313,  314,    0,  316,  298,  317,  300,  318,  319,    0,
      320,  302,  321,    0,  322,  323,  325,  336,  304,  329,
      330,  331,  305,  332,  333,  307,  337,  308,  338,  311,
      343,  313,  314,  316,  344,  317,  346,  318,  347,  319,

      320,  349,  350,  321,  322,  323,  353,  325,  336,  329,
      330,  331,  357,  332,  333,  359,    0,  337,  338,    0,
      343,    0,    0,    0,    0,  344,  346,    0,    0,  347,
        0,    0,  349,  350,    0,    0,    0,  353,    0,    0,
        0,    0,  357,    0,    0,  359,  367,  367,  367,  367,
      367,  367,  368,  368,  368,  368,  368,  368,  369,  369,
      369,  369,  369,  369,  370,  370,  370,  370,  370,  370,
      371,  371,  371,  372,    0,  372,  372,  372,  372,  373,
      373,    0,  373,  373,  373,  375,    0,  375,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[64] =
    {   0,
0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "eiffel.flex"
#line 2 "eiffel.flex"
	#include <stdlib.h>
	#include <stdio.h>
	#include <string.h>
	#include <conio.h>
	#include <locale.h> 

	#include "lexHelpers.h"

#line 819 "eiffel.flex.c"

#line 821 "eiffel.flex.c"

#define INITIAL 0
#define SPECIAL_CHAR 1
#define SINGLE_QUOTED_CHAR 2
#define DOUBLE_QUOTED_STRING 3
#define SINGLE_LINE_COMMENT 4

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 50 "eiffel.flex"



#line 54 "eiffel.flex"
	int startLine = 0;
	char literal[1000];


#line 1048 "eiffel.flex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 367 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 366 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 58 "eiffel.flex"
{ BEGIN(SINGLE_QUOTED_CHAR); literal[0] = '\0'; startLine = yylineno; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 59 "eiffel.flex"
{ strcat(literal, yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 60 "eiffel.flex"
{ if(strlen(literal) == 1) {printf("Found single quoted literal \'%c\'. From line %d to line %d\n", literal[0], startLine, yylineno); } else {
 printf("Invalid single quoted literal \'%s\' at line %d\n", literal, yylineno); }
 BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "eiffel.flex"
{ BEGIN(DOUBLE_QUOTED_STRING); literal[0] = '\0'; startLine = yylineno; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 65 "eiffel.flex"
{ strcat(literal, yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "eiffel.flex"
{ printf("Found double quoted literal \"%s\". From line %d to line %d\n", literal, startLine, yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 68 "eiffel.flex"
{ append_special_char_by_code(literal, yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 69 "eiffel.flex"
{ append_special_char_digraph(literal, yytext);}
	YY_BREAK
case YY_STATE_EOF(SINGLE_QUOTED_CHAR):
case YY_STATE_EOF(DOUBLE_QUOTED_STRING):
#line 71 "eiffel.flex"
{ printf("Unterminated string or char literal at line %d\n", yylineno);  BEGIN(INITIAL);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "eiffel.flex"
{ BEGIN(SINGLE_LINE_COMMENT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 74 "eiffel.flex"
/* skip */
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 75 "eiffel.flex"
{ printf("Found a comment\n"); BEGIN(INITIAL);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 77 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "ASSIGN", yylineno); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 78 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "EQUALS", yylineno); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 79 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "NOT_EQUALS", yylineno); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 80 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "BIT_EQUALS", yylineno); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 81 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "BIT_NOT_EQUALS", yylineno); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 82 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "INT_INTERVAL", yylineno); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 83 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "CHAR_INTERVAL", yylineno); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 84 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "LESS", yylineno); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 85 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "LESS_OR_EQUAL", yylineno); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 86 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "GREATER", yylineno); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 87 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "GREATER_OR_EQUAL", yylineno); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 88 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "AND", yylineno); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 89 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "XOR", yylineno); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 90 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "OR", yylineno); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 91 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "NOT", yylineno); }
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 92 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "AND_THEN", yylineno); }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 93 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "OR_ELSE", yylineno); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 94 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "IMPLIES", yylineno); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 95 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "DIV", yylineno); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 96 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "MOD", yylineno); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 98 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 99 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 100 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 101 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 102 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 103 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 105 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 106 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 107 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 108 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 109 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 110 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 111 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 112 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 113 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 114 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 115 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 116 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 118 "eiffel.flex"
{ printf("Found keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 119 "eiffel.flex"
{ printf("Found boolean value \"%d\" in line %d\n", true, yylineno); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 120 "eiffel.flex"
{ printf("Found boolean value \"%d\" in line %d\n", false, yylineno); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 121 "eiffel.flex"
{ printf("Found null-value \"%s\" in line %d\n", "<void>", yylineno); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 122 "eiffel.flex"
{ printf("Found identifier \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 124 "eiffel.flex"
{ printf("Found exponent value \"%e\" in line %d\n", yy_parse_real(yytext), yylineno); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 125 "eiffel.flex"
{ printf("Found int value \"%d\" in line %d\n", yy_parse_int(yytext), yylineno); /*{NATURAL}	{ printf("Found unsigned int value \"%s\" in line %d\n", yytext, yylineno); }*/ }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 126 "eiffel.flex"
{ printf("Found int value \"%d\" in line %d\n", yy_parse_int(yytext, 'x'), yylineno);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 127 "eiffel.flex"
{ printf("Found int value \"%d\" in line %d\n", yy_parse_int(yytext, 'c'), yylineno);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 128 "eiffel.flex"
{ printf("Found int value \"%d\" in line %d\n", yy_parse_int(yytext, 'b'), yylineno);}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 130 "eiffel.flex"
{ printf("Found real value \"%f\" in line %d\n", yy_parse_real(yytext), yylineno);}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 132 "eiffel.flex"
{ /* skip  {WHITESPACE} */ }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 134 "eiffel.flex"
{ printf("Unexpected char \'%c\' encountered at line %d\n", yytext, yylineno);  BEGIN(INITIAL);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 135 "eiffel.flex"
ECHO;
	YY_BREAK
#line 1441 "eiffel.flex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SPECIAL_CHAR):
case YY_STATE_EOF(SINGLE_LINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 367 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 367 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 366);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 135 "eiffel.flex"

