#line 1 "eiffel.flex.c"

#line 3 "eiffel.flex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[359] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       63,   62,   61,   49,    5,   50,    1,   39,   40,   35,
       33,   47,   34,   46,   36,   56,   56,   45,   38,   20,
       14,   22,   48,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   43,   32,   44,   37,   41,   62,   42,   16,    3,
        3,    4,    3,    6,    7,   62,   11,   12,   61,    0,
       10,   60,   31,   15,   17,   60,   56,    0,    0,    0,
        0,    0,   13,   21,   23,   54,   54,   54,   54,   51,
       54,   54,   54,   54,   54,   54,   54,   51,   54,   54,

       54,   54,   54,   54,   51,   54,   54,   54,   54,   54,
       54,   54,   54,   26,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,    0,    9,    9,    2,   19,
       60,    0,   60,   59,   58,    0,   55,   57,   54,   54,
       51,   24,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   51,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   27,   54,   51,   54,
       54,    0,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   25,    0,
        0,   60,    0,   59,    0,   58,    0,   57,    0,   54,

       54,    0,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   51,   54,   54,   54,   54,   54,   54,   51,   54,
       54,   54,   54,   54,   51,   54,   51,   51,   54,   51,
       51,    0,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   51,   52,   54,   54,   54,   54,   53,   51,   18,
        8,    0,   51,   51,    0,   54,   54,   51,   51,   54,
       54,   54,   51,   54,   54,   54,   54,   54,   54,   52,
       54,   54,   54,   54,   54,   54,   51,   54,    0,   54,
       54,   54,   54,   54,   54,   51,   54,   54,   51,   54,
       51,   54,    0,    0,   51,   54,   54,   51,   54,   54,

       51,   51,   54,   51,   54,   54,   51,   54,   54,   54,
       54,   54,    0,   54,   54,   51,   54,   51,   51,   51,
       54,   54,   54,    0,   54,   51,   51,   54,   54,   54,
       51,   30,   51,   51,   54,   54,   29,   54,   54,   51,
       54,   54,   51,   28,   54,   51,   51,   51,   54,   51,
       54,   51,   51,   51,   51,   51,   51,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,    1,   58,   59,   60,   61,

       62,   63,   64,   65,   66,   36,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
       81,   82,   83,   84,   85,   86,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[87] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1,    1,    1,    5,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[367] =
    {   0,
        0,    0,    0,    0,   80,   82,   86,   87,  277,  268,
      268,  823,   93,  823,  823,  823,  823,  823,  823,  823,
      823,  823,  250,   80,   85,  157,   87,  203,  823,  188,
      823,  184,  823,   77,    0,   86,   88,   88,  104,  141,
      126,   71,  156,   69,  108,  133,  155,   76,  160,  148,
       84,  823,  823,  823,  823,  823,  178,  823,  823,  823,
      167,  823,  139,  823,  823,  153,  823,  823,  188,  150,
      823,  216,  823,  823,  823,  221,  231,  188,  204,  241,
        0,  225,  823,  823,  823,    0,  194,  219,  233,  153,
      219,  235,  240,  229,  239,  228,  247,    0,  229,  246,

      244,  243,  250,  243,    0,  247,  278,  255,  274,  254,
      260,  266,  280,  322,  282,  306,  290,  298,  270,  289,
      308,  289,  302,  308,  297,  125,  823,  355,  823,  823,
      368,  372,  376,  347,  383,  391,  395,   80,  310,  339,
        0,  375,  368,  354,  376,  371,  369,  379,  374,  372,
      389,  390,    0,  376,  400,  393,  381,  385,  393,  397,
      408,  400,  416,  419,  427,  415,  428,  422,    0,  429,
      413,  464,  439,  438,  446,  429,  450,  433,  447,  453,
      442,  452,  448,  453,  453,  454,  462,  458,    0,   48,
      513,  517,  521,  485,  500,  526,  532,   64,   57,  476,

      479,  544,  492,  518,  518,  513,  529,  516,  532,  531,
      522,  532,  525,  530,  527,  528,  542,  528,    0,  545,
      542,  536,  550,  542,    0,  549,    0,    0,  555,    0,
        0,  559,  556,  550,  567,  574,  564,  576,  564,  589,
      577,    0,    0,  588,  590,  586,  598,    0,    0,  823,
      823,  612,    0,    0,  592,  594,  607,    0,    0,  593,
      607,  602,    0,  599,  607,  615,  617,  606,  615,    0,
      614,  619,  617,  625,  632,  627,    0,  632,  620,  624,
      636,  643,  632,  649,  637,    0,  638,  654,    0,  651,
        0,  650,   95,  656,    0,  649,  651,    0,  653,  669,

        0,    0,  670,    0,  676,  673,    0,  662,  662,  663,
      683,  669,  685,  674,  681,    0,  691,    0,    0,    0,
      678,  685,  682,  690,  687,    0,    0,  706,  710,  704,
        0,    0,    0,    0,  703,  713,  823,  705,  717,    0,
      719,  721,    0,  823,  725,    0,    0,    0,  713,    0,
      717,    0,    0,    0,    0,    0,    0,  823,  791,  796,
      801,  806,  809,  814,  100,  817
    } ;

static const flex_int16_t yy_def[367] =
    {   0,
      358,    1,  359,  359,  360,  360,  361,  361,  362,  362,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      364,  358,  358,  358,  358,  364,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      365,  358,  358,  358,  358,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  366,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  358,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  358,
      358,  358,  358,  358,  358,  358,  358,  366,  366,  363,

      363,  358,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  358,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  358,
      358,  358,  363,  363,  358,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  358,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  358,  358,  363,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  358,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  358,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  358,  363,  363,  363,
      363,  363,  363,  358,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,    0,  358,  358,
      358,  358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_nxt[910] =
    {   0,
       12,   13,   13,   14,   15,   16,   12,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   27,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   35,   35,   40,   35,   35,   41,   35,   42,
       43,   44,   35,   45,   46,   47,   48,   49,   50,   51,
       35,   35,   52,   53,   54,   55,   12,   34,   35,   36,
       37,   38,   39,   35,   35,   40,   35,   41,   35,   42,
       43,   44,   35,   45,   46,   47,   48,   49,   50,   51,
       35,   35,   56,   57,   58,   59,   61,   62,   61,   62,
       65,   65,   66,   66,   69,   69,   72,   72,   72,   72,

       73,   76,  138,   77,   77,   77,   77,   70,   74,   87,
      251,  110,  115,  199,   88,  121,   89,   80,   97,   92,
      199,   90,   91,   93,  125,   99,   94,  100,   98,   95,
      102,  250,   96,   63,  103,   63,  199,  101,  116,  190,
       87,  110,  115,   82,   88,  121,   89,  104,   80,   97,
       92,   90,   91,   93,  125,   99,   94,  100,   98,   95,
      108,  102,   96,  117,  130,  103,  109,  101,  128,  116,
       75,   76,  105,   77,   77,   77,   77,  104,  129,  106,
      107,  124,  128,  111,   78,   79,  122,   80,  118,   69,
       69,  108,  126,  112,  117,  113,  109,  143,  119,  114,

      123,  120,   70,  105,  134,  134,   81,   85,  129,  106,
      107,   84,  124,   82,  111,   78,   79,  122,   80,  118,
      135,  135,  135,  112,  139,  113,   83,  143,  119,  114,
      123,  120,  131,  131,  131,  131,   81,  133,  133,  133,
      133,   77,   77,   77,   77,   76,   80,   77,   77,   77,
       77,   80,  136,  140,  136,  139,  141,  137,  137,  137,
      137,   80,  142,   71,  144,  145,  146,  358,  147,  148,
       68,  149,  132,  152,  150,  153,  158,   80,  151,   68,
      157,   82,   80,  159,  140,  155,  141,   82,  160,  156,
      154,  164,   80,  142,  144,  169,  145,  146,  147,  167,

      148,  149,  165,  152,  168,  150,  153,  158,  170,  151,
      157,  161,  173,  159,  166,  155,  182,  171,  160,  156,
      154,  164,  162,  172,  172,  163,  169,  179,  181,  167,
      183,  180,  186,  165,  168,  174,  187,  184,  188,  170,
      189,  358,  161,  173,  166,  175,  182,  171,  176,  200,
      177,  178,  162,  185,  358,  163,  358,  179,  358,  181,
      183,  180,  186,  194,  194,  201,  174,  187,  184,  188,
      189,  191,  191,  191,  191,  175,  202,  202,  176,  200,
      177,  178,  358,  185,  131,  131,  131,  131,  131,  131,
      131,  131,  192,  192,  192,  192,  201,  204,   80,  196,

      196,  196,  203,  195,  205,  208,   80,  137,  137,  137,
      137,  137,  137,  137,  137,  206,  207,  209,  210,  211,
      212,  358,  213,  216,  132,  217,  214,  204,  132,   80,
      218,  219,  193,  203,  221,  205,  208,   80,  222,  197,
      215,  223,  224,  358,  220,  206,  207,  209,  210,  225,
      211,  212,  213,  226,  216,  217,  227,  214,  228,  230,
      218,  219,  229,  231,  221,  172,  172,  233,  234,  222,
      215,  223,  235,  224,  220,  236,  239,  240,  237,  241,
      225,  242,  243,  245,  226,  244,  227,  246,  247,  228,
      230,  248,  229,  231,  232,  358,  238,  249,  233,  234,

      358,  194,  194,  235,  358,  236,  239,  358,  240,  237,
      241,  242,  358,  243,  245,  244,  194,  194,  246,  247,
      358,  253,  248,  254,  256,  232,  238,  249,  251,  252,
      252,  252,  252,  192,  192,  192,  192,  192,  192,  192,
      192,  195,  196,  196,  196,  202,  202,   80,  196,  196,
      196,  253,  257,  254,  258,  256,  195,  259,  358,  260,
      358,  261,  262,  263,  358,  264,  265,  358,  266,  267,
      268,  269,  270,  193,  271,  272,  273,  193,   80,  274,
      275,  281,  197,  257,  258,  276,  277,  259,  197,  255,
      260,  261,  278,  262,  263,  264,  279,  265,  266,  267,

      268,  269,  280,  270,  271,  282,  272,  273,  283,  274,
      284,  275,  281,  285,  286,  276,  277,  287,  289,  255,
      288,  290,  278,  291,  292,  294,  279,  251,  293,  293,
      293,  293,  280,  295,  296,  282,  297,  298,  301,  283,
      284,  299,  300,  285,  286,  302,  303,  308,  287,  289,
      288,  304,  290,  291,  305,  292,  294,  306,  307,  309,
      310,  311,  312,  295,  313,  296,  297,  314,  298,  301,
      315,  299,  300,  316,  358,  317,  302,  303,  308,  318,
      321,  304,  319,  320,  305,  322,  324,  306,  307,  323,
      309,  310,  311,  312,  313,  325,  326,  314,  327,  328,

      329,  315,  330,  331,  316,  317,  332,  333,  334,  335,
      318,  321,  319,  320,  336,  337,  322,  324,  338,  323,
      339,  340,  358,  341,  342,  325,  326,  343,  327,  344,
      328,  329,  345,  330,  331,  346,  332,  333,  334,  347,
      335,  348,  349,  350,  336,  351,  337,  352,  338,  353,
      339,  354,  340,  341,  342,  355,  358,  343,  356,  344,
      357,  358,  345,  358,  358,  358,  346,  358,  358,  358,
      347,  348,  349,  358,  350,  351,  358,  358,  352,  358,
      353,  358,  354,  358,  358,  358,  355,  358,  356,  358,
      357,   12,   12,   12,   12,   12,   60,   60,   60,   60,

       60,   64,   64,   64,   64,   64,   67,   67,   67,   67,
       67,   86,   86,   86,  127,  358,  127,  127,  127,  198,
      358,  198,   11,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_chk[910] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    6,    6,
        7,    8,    7,    8,   13,   13,   24,   24,   24,   24,

       25,   27,  365,   27,   27,   27,   27,   13,   25,   34,
      293,   42,   44,  199,   34,   48,   34,   27,   37,   36,
      198,   34,   34,   36,   51,   38,   36,   38,   37,   36,
       39,  190,   36,    5,   39,    6,  138,   38,   45,  126,
       34,   42,   44,   27,   34,   48,   34,   39,   27,   37,
       36,   34,   34,   36,   51,   38,   36,   38,   37,   36,
       41,   39,   36,   46,   70,   39,   41,   38,   66,   45,
       25,   26,   40,   26,   26,   26,   26,   39,   63,   40,
       40,   50,   61,   43,   26,   26,   49,   26,   47,   69,
       69,   41,   57,   43,   46,   43,   41,   90,   47,   43,

       49,   47,   69,   40,   78,   78,   26,   32,   63,   40,
       40,   30,   50,   26,   43,   26,   26,   49,   26,   47,
       79,   79,   79,   43,   87,   43,   28,   90,   47,   43,
       49,   47,   72,   72,   72,   72,   26,   76,   76,   76,
       76,   82,   82,   82,   82,   77,   72,   77,   77,   77,
       77,   76,   80,   88,   80,   87,   88,   80,   80,   80,
       80,   77,   89,   23,   91,   92,   93,   11,   94,   95,
       10,   96,   72,   99,   97,  100,  103,   72,   97,    9,
      102,   82,   76,  104,   88,  101,   88,   77,  106,  101,
      100,  108,   77,   89,   91,  112,   92,   93,   94,  110,

       95,   96,  109,   99,  111,   97,  100,  103,  113,   97,
      102,  107,  115,  104,  109,  101,  119,  113,  106,  101,
      100,  108,  107,  114,  114,  107,  112,  117,  118,  110,
      120,  117,  122,  109,  111,  116,  123,  121,  124,  113,
      125,    0,  107,  115,  109,  116,  119,  113,  116,  139,
      116,  116,  107,  121,    0,  107,    0,  117,    0,  118,
      120,  117,  122,  134,  134,  140,  116,  123,  121,  124,
      125,  128,  128,  128,  128,  116,  142,  142,  116,  139,
      116,  116,    0,  121,  131,  131,  131,  131,  132,  132,
      132,  132,  133,  133,  133,  133,  140,  144,  131,  135,

      135,  135,  143,  134,  145,  148,  133,  136,  136,  136,
      136,  137,  137,  137,  137,  146,  147,  149,  150,  151,
      152,    0,  154,  156,  131,  157,  155,  144,  132,  131,
      158,  159,  133,  143,  160,  145,  148,  133,  161,  135,
      155,  162,  163,    0,  159,  146,  147,  149,  150,  164,
      151,  152,  154,  165,  156,  157,  166,  155,  167,  170,
      158,  159,  168,  171,  160,  172,  172,  173,  174,  161,
      155,  162,  175,  163,  159,  176,  178,  179,  177,  180,
      164,  181,  182,  184,  165,  183,  166,  185,  186,  167,
      170,  187,  168,  171,  172,    0,  177,  188,  173,  174,

        0,  194,  194,  175,    0,  176,  178,    0,  179,  177,
      180,  181,    0,  182,  184,  183,  195,  195,  185,  186,
        0,  200,  187,  201,  203,  172,  177,  188,  191,  191,
      191,  191,  191,  192,  192,  192,  192,  193,  193,  193,
      193,  194,  196,  196,  196,  202,  202,  192,  197,  197,
      197,  200,  204,  201,  205,  203,  195,  206,    0,  207,
        0,  208,  209,  210,    0,  211,  212,    0,  213,  214,
      215,  216,  217,  192,  218,  220,  221,  193,  192,  222,
      223,  234,  196,  204,  205,  224,  226,  206,  197,  202,
      207,  208,  229,  209,  210,  211,  232,  212,  213,  214,

      215,  216,  233,  217,  218,  235,  220,  221,  236,  222,
      237,  223,  234,  238,  239,  224,  226,  240,  244,  202,
      241,  245,  229,  246,  247,  255,  232,  252,  252,  252,
      252,  252,  233,  256,  257,  235,  260,  261,  265,  236,
      237,  262,  264,  238,  239,  266,  267,  273,  240,  244,
      241,  268,  245,  246,  269,  247,  255,  271,  272,  274,
      275,  276,  278,  256,  279,  257,  260,  280,  261,  265,
      281,  262,  264,  282,    0,  283,  266,  267,  273,  284,
      288,  268,  285,  287,  269,  290,  294,  271,  272,  292,
      274,  275,  276,  278,  279,  296,  297,  280,  299,  300,

      303,  281,  305,  306,  282,  283,  308,  309,  310,  311,
      284,  288,  285,  287,  312,  313,  290,  294,  314,  292,
      315,  317,    0,  321,  322,  296,  297,  323,  299,  324,
      300,  303,  325,  305,  306,  328,  308,  309,  310,  329,
      311,  330,  335,  336,  312,  338,  313,  339,  314,  341,
      315,  342,  317,  321,  322,  345,    0,  323,  349,  324,
      351,    0,  325,    0,    0,    0,  328,    0,    0,    0,
      329,  330,  335,    0,  336,  338,    0,    0,  339,    0,
      341,    0,  342,    0,    0,    0,  345,    0,  349,    0,
      351,  359,  359,  359,  359,  359,  360,  360,  360,  360,

      360,  361,  361,  361,  361,  361,  362,  362,  362,  362,
      362,  363,  363,  363,  364,    0,  364,  364,  364,  366,
        0,  366,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[63] =
    {   0,
0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "eiffel.flex"
#line 2 "eiffel.flex"
	#include <stdlib.h>
	#include <stdio.h>
	#include <string.h>
	#include <conio.h>
	#include <locale.h> 

	#include "lexHelpers.h"

#line 802 "eiffel.flex.c"

#line 804 "eiffel.flex.c"

#define INITIAL 0
#define SPECIAL_CHAR 1
#define SINGLE_QUOTED_CHAR 2
#define DOUBLE_QUOTED_STRING 3
#define SINGLE_LINE_COMMENT 4

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 49 "eiffel.flex"



#line 53 "eiffel.flex"
	int startLine = 0;
	char literal[1000];


#line 1031 "eiffel.flex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 359 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 358 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "eiffel.flex"
{ BEGIN(SINGLE_QUOTED_CHAR); literal[0] = '\0'; startLine = yylineno; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "eiffel.flex"
{ strcat(literal, yytext);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 59 "eiffel.flex"
{ strcat(literal, yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "eiffel.flex"
{ printf("Found single quoted literal \"%s\". From line %d to line %d\n", literal, startLine, yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 62 "eiffel.flex"
{ BEGIN(DOUBLE_QUOTED_STRING); literal[0] = '\0'; startLine = yylineno; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 63 "eiffel.flex"
{ strcat(literal, yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 64 "eiffel.flex"
{ printf("Found double quoted literal \"%s\". From line %d to line %d\n", literal, startLine, yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "eiffel.flex"
{ append_special_char_by_code(literal, yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 "eiffel.flex"
{ append_special_char_digraph(literal, yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 69 "eiffel.flex"
{ BEGIN(SINGLE_LINE_COMMENT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 70 "eiffel.flex"
/* skip */
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 71 "eiffel.flex"
{ printf("Found a comment\n"); BEGIN(INITIAL);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "ASSIGN", yylineno); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "EQUALS", yylineno); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "NOT_EQUALS", yylineno); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "BIT_EQUALS", yylineno); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "BIT_NOT_EQUALS", yylineno); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "INT_INTERVAL", yylineno); }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 79 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "CHAR_INTERVAL", yylineno); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "LESS", yylineno); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "LESS_OR_EQUAL", yylineno); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "GREATER", yylineno); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "GREATER_OR_EQUAL", yylineno); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "AND", yylineno); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "XOR", yylineno); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 86 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "OR", yylineno); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 87 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "NOT", yylineno); }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 88 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "AND_THEN", yylineno); }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 89 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "OR_ELSE", yylineno); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 90 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "IMPLIES", yylineno); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 91 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "DIV", yylineno); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 92 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", "MOD", yylineno); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 94 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 95 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 96 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 97 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 99 "eiffel.flex"
{ printf("Found operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "eiffel.flex"
{ printf("Found symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 114 "eiffel.flex"
{ printf("Found keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 115 "eiffel.flex"
{ printf("Found boolean value \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 116 "eiffel.flex"
{ printf("Found null-value \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 117 "eiffel.flex"
{ printf("Found identifier \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 119 "eiffel.flex"
{ printf("Found exponent value \"%e\" in line %d\n", yy_parse_real(yytext), yylineno); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 120 "eiffel.flex"
{ printf("Found int value \"%d\" in line %d\n", yy_parse_int(yytext), yylineno); /*{NATURAL}	{ printf("Found unsigned int value \"%s\" in line %d\n", yytext, yylineno); }*/ }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 121 "eiffel.flex"
{ printf("Found int value \"%d\" in line %d\n", yy_parse_int(yytext, 'x'), yylineno);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 122 "eiffel.flex"
{ printf("Found int value \"%d\" in line %d\n", yy_parse_int(yytext, 'c'), yylineno);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 123 "eiffel.flex"
{ printf("Found int value \"%d\" in line %d\n", yy_parse_int(yytext, 'b'), yylineno);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 125 "eiffel.flex"
{ printf("Found real value \"%f\" in line %d\n", yy_parse_real(yytext), yylineno); }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 127 "eiffel.flex"
{ /* skip  {WHITESPACE} */ }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 128 "eiffel.flex"
ECHO;
	YY_BREAK
#line 1412 "eiffel.flex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SPECIAL_CHAR):
case YY_STATE_EOF(SINGLE_QUOTED_CHAR):
case YY_STATE_EOF(DOUBLE_QUOTED_STRING):
case YY_STATE_EOF(SINGLE_LINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 359 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 359 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 358);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 128 "eiffel.flex"

