/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
static yyconst short int yy_acclist[270] =
    {   0,
        8,    8,   88,    1,   87,   87,   87,   45,   87,    6,
       87,   66,   87,   49,   87,   87,   11,   87,   68,   87,
       69,   87,   46,   87,   50,   87,   53,   87,   54,   87,
       51,   87,   48,   87,   81,   83,   87,   81,   83,   87,
       81,   87,   52,   87,   67,   87,   55,   87,   65,   87,
       57,   87,   87,   77,   87,   77,   87,   77,   87,   77,
       87,   72,   87,   73,   87,   77,   87,   77,   87,   77,
       87,   77,   87,   77,   87,   77,   87,   77,   87,   77,
       87,   77,   87,   77,   87,   77,   87,   77,   87,   77,
       87,   77,   87,   70,   87,   87,   71,   87,    8,   87,

        9,   87,    3,   87,    4,   87,   15,   87,   16,   87,
       87,   17,   60,    6,   63,   47,   43,   44,   75,   85,
        7,    6,   85,   83,   81,   83,   81,   74,   56,   59,
       76,   58,   19,   77,   77,   77,   77,   77,   26,   77,
       77,   77,   77,   32,   77,   77,   77,   77,   77,   37,
       77,   77,   28,   77,   77,   77,   77,   77,   77,   77,
       64,    8,    9,    9,   10,    3,   14,   13,   12,   62,
       85,   86,   82,   84,   18,   61,   77,   77,   77,   27,
       77,   77,   77,   77,   77,   77,   34,   77,   77,   25,
       77,   77,   77,   77,   77,   77,   77,   29,   77,    5,

        2,   77,   77,   80,   77,   78,   77,   77,   77,   77,
       36,   77,   39,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   17,   77,   79,   30,   77,   21,   77,   20,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       33,   77,   77,   38,   77,   77,   77,   77,   77,   22,
       77,   41,   77,   42,   77,   77,   35,   77,   77,   24,
       77,   77,   31,   77,   40,   77,   77,   23,   77
    } ;

static yyconst short int yy_accept[215] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    3,
        3,    3,    3,    4,    6,    7,    8,   10,   12,   14,
       16,   17,   19,   21,   23,   25,   27,   29,   31,   33,
       35,   38,   41,   43,   45,   47,   49,   51,   53,   54,
       56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
       76,   78,   80,   82,   84,   86,   88,   90,   92,   94,
       96,   97,   99,  101,  103,  105,  107,  109,  111,  112,
      112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
      122,  123,  124,  125,  125,  125,  125,  125,  127,  128,
      129,  129,  130,  130,  131,  132,  133,  134,  135,  136,

      137,  138,  139,  141,  142,  143,  144,  146,  147,  148,
      149,  150,  152,  153,  155,  156,  157,  158,  159,  160,
      161,  162,  163,  164,  165,  166,  167,  167,  168,  169,
      170,  170,  170,  171,  172,  172,  173,  174,  175,  176,
      177,  178,  179,  180,  182,  183,  184,  185,  186,  187,
      189,  190,  192,  193,  194,  195,  196,  197,  198,  200,
      201,  202,  202,  203,  205,  207,  208,  209,  210,  211,
      213,  215,  216,  217,  218,  219,  220,  221,  222,  223,
      224,  226,  228,  230,  232,  233,  234,  235,  236,  237,
      238,  239,  240,  241,  243,  244,  246,  247,  248,  249,

      250,  252,  254,  256,  257,  259,  260,  262,  263,  265,
      267,  268,  270,  270
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    4,    5,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   33,   31,   31,
       31,   34,   35,   36,   37,   31,   31,   38,   31,   31,
       39,   40,   41,    1,   31,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   48,   51,   52,   48,   53,
       54,   55,   48,   56,   57,   58,   59,   60,   61,   62,
       48,   48,   63,   64,   65,    1,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,

       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31
    } ;

static yyconst int yy_meta[66] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    4,    1,    5,    6,    6,    6,    6,
        1,    1,    1,    5,    1,    1,    6,    6,    6,    6,
        7,    7,    7,    7,    7,    7,    7,    7,    1,    1,
        1,    8,    8,    8,    8,    8,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    1,    1,    1
    } ;

static yyconst short int yy_base[226] =
    {   0,
        0,    2,   57,    0,    0,    0,  412,  411,  407,  406,
        0,  115,  419,  424,  424,    1,  394,    0,  424,  424,
      410,  424,  424,  424,  405,  403,  424,    4,    2,   19,
      154,  110,  116,  393,  424,    0,    7,  389,  387,    0,
        6,   87,    0,  424,  424,   84,  355,    0,  356,   88,
      111,  362,  105,  352,   88,  361,  348,  356,  350,  424,
      339,  424,    0,   25,    0,  388,  424,  424,  135,  387,
      345,  375,    0,  424,  424,  424,  424,  424,  160,  424,
        0,  167,  190,  203,   25,    0,   29,  209,  222,  424,
      133,  424,  134,  374,  424,  424,  424,    0,  129,  150,

       89,  352,    0,  350,  353,  341,    0,  344,  335,  335,
      337,    0,  328,    0,  113,  345,  329,  344,  335,  328,
      424,    0,  179,  182,  424,    0,  358,  424,  424,  424,
      368,  332,  424,  227,  240,  244,    0,  186,  424,  424,
      119,  159,  185,    0,  338,  322,  176,  324,  331,  330,
      331,    0,  314,  315,  320,  312,  312,  317,    0,  424,
      424,  313,  206,    0,    0,  316,  308,  300,  289,    0,
      280,  287,  262,  230,  225,  220,  213,  217,  220,  424,
        0,    0,    0,    0,  212,  207,  209,  200,  190,  199,
      186,  172,  173,    0,  156,    0,  163,  147,  153,  136,

        0,    0,    0,  120,    0,  107,    0,  106,    0,    0,
        5,    0,  424,  273,  282,  291,  300,  309,  318,  323,
      327,  336,  345,  354,  358
    } ;

static yyconst short int yy_def[226] =
    {   0,
      214,  214,  213,    3,  215,  215,  216,  216,  217,  217,
      218,  218,  213,  213,  213,  213,  213,  219,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  220,  213,  213,  213,  221,
      221,  221,  221,  213,  213,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  213,
      213,  213,  222,  223,  224,  213,  213,  213,  213,  213,
      213,  213,  219,  213,  213,  213,  213,  213,  213,  213,
      219,  213,  213,  213,  213,  225,  213,  213,  213,  213,
      220,  213,  220,  213,  213,  213,  213,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      213,  222,  223,  223,  213,  224,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  225,  213,  213,  213,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  213,
      213,  213,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  213,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,    0,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213
    } ;

static yyconst short int yy_nxt[490] =
    {   0,
      213,  213,  213,   70,  213,  213,  213,   68,   15,   15,
       15,   15,  213,  213,  213,   91,  213,   77,   79,   79,
       79,   79,   16,   92,   16,   15,   71,   15,   78,   80,
       94,   95,   99,  101,   81,  124,  135,  213,  135,   69,
      125,  136,  136,  136,  136,  138,  138,   99,   15,  212,
       15,  105,   15,  106,   15,  101,   15,   15,   15,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   40,   40,   41,   40,   40,   42,
       40,   40,   43,   40,   40,   44,   15,   45,   46,   47,

       48,   49,   50,   51,   40,   40,   52,   40,   40,   53,
       54,   55,   56,   57,   43,   40,   40,   58,   59,   60,
       61,   62,   68,  100,   82,  143,   88,   88,   88,   89,
       82,  108,   89,   89,   89,   89,  102,   99,   85,  109,
      103,  100,  128,  115,   85,  100,  116,  143,  213,  213,
      113,  211,   99,  163,   69,   85,  213,  213,  139,  210,
      141,   85,  153,  100,  110,  209,  154,   15,   82,  111,
       83,   83,   83,   84,  129,  163,   79,   79,   79,   79,
      141,  142,   85,  134,  134,  134,  134,  130,   85,  213,
      164,   86,  124,  208,  213,   85,   87,  125,  207,   85,

      206,  142,  138,  138,   82,   85,   83,   83,   83,   84,
      164,  205,   85,  165,  204,   86,  203,   82,   85,   84,
       84,   84,   84,   82,  202,   88,   88,   88,   89,  201,
      165,   85,  168,  169,  181,   85,   82,   85,   89,   89,
       89,   89,  200,  134,  134,  134,  134,  199,   85,  198,
       85,  181,  197,  196,   85,   85,  136,  136,  136,  136,
      136,  136,  136,  136,  195,  194,  193,   85,  192,  191,
      190,  189,   85,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   63,   63,   63,   63,   63,   63,   63,   63,   63,

       65,   65,   65,   65,   65,   65,   65,   65,   65,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   73,  188,
       73,   73,   73,   73,   73,   73,   73,   93,  187,  186,
       93,   93,   98,   98,   98,   98,  122,  122,  185,  122,
      122,  122,  122,  122,  122,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  126,  126,  126,  184,  126,  126,
      126,  126,  126,  137,  183,  137,  182,  180,  179,  178,
      177,  176,  175,  174,  173,  172,  171,  170,  167,  166,
      162,  161,  160,  159,  158,  157,  156,  155,  152,  151,
      150,  149,  148,  147,  146,  145,  144,  140,  133,  132,

      131,  127,  121,  120,  119,  118,  117,  114,  112,  107,
      104,   97,   96,   90,   76,   75,   74,   72,  213,   66,
       66,   64,   64,   13,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213
    } ;

static yyconst short int yy_chk[490] =
    {   0,
        0,    0,    0,   16,    0,    0,    0,   11,    1,    1,
        2,    2,    0,    0,    0,   36,    0,   28,   29,   29,
       29,   29,    1,   36,    2,    1,   16,    2,   28,   30,
       37,   37,   41,   43,   30,   64,   85,    0,   85,   11,
       64,   85,   85,   85,   85,   87,   87,   41,    1,  211,
        2,   48,   11,   48,    1,   43,    2,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,   12,   42,   32,  101,   32,   32,   32,   32,
       33,   50,   33,   33,   33,   33,   46,   51,   32,   50,
       46,   53,   69,   55,   33,   42,   55,  101,   91,   93,
       53,  208,   51,  141,   12,   32,   91,   93,   93,  206,
       99,   33,  115,   53,   51,  204,  115,   12,   31,   51,
       31,   31,   31,   31,   69,  141,   79,   79,   79,   79,
       99,  100,   31,   82,   82,   82,   82,   69,   79,  123,
      142,   31,  124,  200,  123,   82,   31,  124,  199,   31,

      198,  100,  138,  138,   83,   79,   83,   83,   83,   83,
      142,  197,   82,  143,  195,   31,  193,   84,   83,   84,
       84,   84,   84,   88,  192,   88,   88,   88,   88,  191,
      143,   84,  147,  147,  163,   83,   89,   88,   89,   89,
       89,   89,  190,  134,  134,  134,  134,  189,   84,  188,
       89,  163,  187,  186,   88,  134,  135,  135,  135,  135,
      136,  136,  136,  136,  185,  179,  178,   89,  177,  176,
      175,  174,  134,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      217,  217,  217,  217,  217,  217,  217,  217,  217,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  219,  173,
      219,  219,  219,  219,  219,  219,  219,  220,  172,  171,
      220,  220,  221,  221,  221,  221,  222,  222,  169,  222,
      222,  222,  222,  222,  222,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  224,  224,  224,  168,  224,  224,
      224,  224,  224,  225,  167,  225,  166,  162,  158,  157,
      156,  155,  154,  153,  151,  150,  149,  148,  146,  145,
      132,  131,  127,  120,  119,  118,  117,  116,  113,  111,
      110,  109,  108,  106,  105,  104,  102,   94,   72,   71,

       70,   66,   61,   59,   58,   57,   56,   54,   52,   49,
       47,   39,   38,   34,   26,   25,   21,   17,   13,   10,
        9,    8,    7,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "php.flex"
#define INITIAL 0
#line 2 "php.flex"
	#include <math.h>
	#include <stdlib.h>
	#include <stdio.h>
	#include <string.h>
	#include <conio.h>
	#include <locale.h> 
#define YY_NEVER_INTERACTIVE 1
#define PHP 1

#define ONE_LINE_COMMENT 2

#define MULTILINE_COMMENT 3

#define HTML_COMMENT 4

#define SINGLE_QUOTED_STRING 5

#line 603 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 34 "php.flex"



	int s = 0;
	char buf[100000];


#line 758 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 214 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 424 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 41 "php.flex"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "php.flex"
{ BEGIN(HTML_COMMENT); s = yylineno; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 44 "php.flex"
{ ; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "php.flex"
{ ; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "php.flex"
{ BEGIN(INITIAL); printf("Founded HTML-comment from line %d to line %d\n", s, yylineno); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "php.flex"
{ printf("Founded single line comment in line %d\n", yylineno); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "php.flex"
{ BEGIN(MULTILINE_COMMENT); s = yylineno; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "php.flex"
{ ; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 "php.flex"
{ ; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "php.flex"
{ BEGIN(PHP); printf("Founded multiline comment from line %d to line %d\n", s, yylineno); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 55 "php.flex"
{ BEGIN(SINGLE_QUOTED_STRING); buf[0] = '\0'; s = yylineno; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 56 "php.flex"
{ strcat(buf, yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 57 "php.flex"
{ strcat(buf, yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 58 "php.flex"
{ strcat(buf, yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 59 "php.flex"
{ strcat(buf, yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 60 "php.flex"
{ BEGIN(PHP); printf("Founded single quoted literal \"%s\" from line %d to line %d\n", buf, s, yylineno); }
	YY_BREAK
case YY_STATE_EOF(HTML_COMMENT):
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 62 "php.flex"
{ BEGIN(INITIAL); printf("ERROR! Unexpected end of file!"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "php.flex"
{ BEGIN(PHP); printf("Founded start PHP-script in line %d\n", yylineno); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "php.flex"
{ printf("ERROR! HTML inside PHP-script in line %d!", yylineno); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "php.flex"
{ BEGIN(INITIAL); printf("Founded end PHP-script in line %d\n", yylineno); }
	YY_BREAK
case YY_STATE_EOF(PHP):
#line 67 "php.flex"
{ BEGIN(INITIAL); printf("Founded end PHP-script in line %d\n", yylineno); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 69 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 70 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 71 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 75 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 76 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 77 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 78 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 79 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 80 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 81 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 82 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 83 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 84 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 85 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 86 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 87 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 88 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 89 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 90 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 91 "php.flex"
{ printf("Finded keyword \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 94 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 95 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 96 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 97 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 98 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 99 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 100 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 101 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 103 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 104 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 105 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 106 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 107 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 108 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 109 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 110 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 111 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 112 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 113 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 114 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 115 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 116 "php.flex"
{ printf("Finded operator \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 118 "php.flex"
{ printf("Finded symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 119 "php.flex"
{ printf("Finded symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 120 "php.flex"
{ printf("Finded symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 121 "php.flex"
{ printf("Finded symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 122 "php.flex"
{ printf("Finded symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 123 "php.flex"
{ printf("Finded symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 124 "php.flex"
{ printf("Finded symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 125 "php.flex"
{ printf("Finded symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 126 "php.flex"
{ printf("Finded symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 127 "php.flex"
{ printf("Finded symbol \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 129 "php.flex"
{ printf("Finded identifier \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 130 "php.flex"
{ printf("Finded boolean value \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 131 "php.flex"
{ printf("Finded boolean value \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 132 "php.flex"
{ printf("Finded value \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 133 "php.flex"
{ printf("Finded int value \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 134 "php.flex"
{ printf("Finded int value \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 135 "php.flex"
{ printf("Finded int value \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 136 "php.flex"
{ printf("Finded int value \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 137 "php.flex"
{ printf("Finded float value \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 138 "php.flex"
{ printf("Finded float value \"%s\" in line %d\n", yytext, yylineno); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 140 "php.flex"
ECHO;
	YY_BREAK
#line 1293 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(ONE_LINE_COMMENT):
			case YY_STATE_EOF(SINGLE_QUOTED_STRING):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 214 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 214 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 213);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 140 "php.flex"
